### PR TITLE
Add some more settings

### PR DESCRIPTION
**Pull request by AzonInc**
I added more settings and sensors.
Unfortunately floats (Number Entites) are limited to 7 decimals which is unfortunate for the lat&long settings.

I commented the definition part out but everything else is still implemented in case somebody has a solution in the future.

Should be enough for now to release a new version :)

### CODE REVIEW

**Comment by AzonInc** [comment]
Would you keep the latitude and longitude parts or remove them completely?

**Comment by uriyacovy** [comment]
Why are they required?

**Comment by AzonInc** [comment]
They're just general settings for auto unlock location

**Comment by uriyacovy** [comment]
Then let's remove completely if they are not really used.

**Comment by AzonInc** [comment]
Okay, done

**Review by uriyacovy — APPROVED** [review]

**Pull request merged**
