### PR TITLE
Pairing Mode Switch, Unpair Button, Automations

### PR DESCRIPTION
**Pull request by andrejsoucek**
Adding AzonInc's fork functions. It no longer works without changes from the original repository so I rebased it.
- added security pin
- pairing more switch
- unpair button
- some automations

### CODE REVIEW

**Comment by andrejsoucek** [comment]
@AzonInc fyi

**Comment by AzonInc** [comment]
I could create a new branch based on dev and add my changes officially but they are also breaking changes regarding the behaviour of pairing mode.

That's the reason why I kept them in my fork for now.

**Comment by AzonInc** [comment]
I have created another PR #56 which also has some corrections in the docs and follows the code style of this repo.

**Comment by uriyacovy** [comment]
Merged https://github.com/uriyacovy/ESPHome_nuki_lock/pull/56

**Pull request closed without merging**
