### PR TITLE
Adding GitHub Action to test each commit and PR

### PR DESCRIPTION
**Pull request by Savjee**
Small quality of life improvement: all commits & pull requests will now be compiled on GitHub Actions to verify that the code is actually valid.

I'm using the official ESPHome GitHub Action here, so maintenance should be minimal.
The only thing that might need to change is this line:

```
- https://github.com/uriyacovy/NukiBleEsp32#dev
```

A thought I had:
* Use the master branch of the library whenever the action is run against the master branch
* Use the "dev" branch for any other branch.

You can see it in action here: https://github.com/Savjee/ESPHome_nuki_lock/actions

### CODE REVIEW

**Comment by uriyacovy** [comment]
Hi @Savjee,
Thanks for yet another great contribution!
Regarding main vs dev - we can go as you suggested (main for main, dev for anything else). 

Just note that the current yaml is not going to work for neither branch. 
1. For dev it should also have the required "is_connected" binary sensor.
2. For main:
  2.1. It should not use NukiBleEsp32#dev but just NukiBleEsp32 
  2.2. You should add https://github.com/nkolban/ESP32_BLE_Arduino/ to libraries
  2.3. You should use the default framework (3.5.0) and not 4.4.0

I think we can also add the door sensor, because it should not fail the build in any case.

**Comment by uriyacovy** [comment]
Hi @Savjee, what do you think?

**Comment by Savjee** [comment]
Oops, forgot about this PR.

1. `is_connected` was already included. See https://github.com/Savjee/ESPHome_nuki_lock/blob/ci/.github/example-project.yaml
2. For main: I have created two sample ESPHome config files in the `.github` folder. One for `main` and one for other branches. I've adapted them to reflect your feedback.
3. Door sensor was added to both. It doesn't break the build indeed.

**Comment by uriyacovy** [comment]
Looks great, Thanks!

**Pull request merged**
